/*
  ==============================================================================

  Copyright (c) 2015-2018 - Maximilian Rest

  Permission is granted to use this software under the terms of either:
  a) the GPL v2 (or any later version)
  b) the Affero GPL v3
  Details of these licenses can be found at: www.gnu.org/licenses
  This Software is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 
  ==============================================================================
*/


#define sample44100Len 97

static const double sample44100[97] = {
                                    0.7886,
                                    0.9900,
                                    0.8993,
                                    0.9624,
                                    0.9160,
                                    0.9493,
                                    0.9269,
                                    0.9406,
                                    0.9336,
                                    0.9359,
                                    0.9365,
                                    0.9345,
                                    0.9368,
                                    0.9347,
                                    0.9364,
                                    0.9351,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9328,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9358,
                                    0.9330,
                                    0.9293,
                                    0.9239,
                                    0.9162,
                                    0.9053,
                                    0.8905,
                                    0.8709,
                                    0.8462,
                                    0.8161,
                                    0.7803,
                                    0.7391,
                                    0.6928,
                                    0.6422,
                                    0.5880,
                                    0.5314,
                                    0.4733,
                                    0.4152,
                                    0.3582,
                                    0.3035,
                                    0.2521,
                                    0.2050,
                                    0.1628,
                                    0.1260,
                                    0.0948,
                                    0.0691,
                                    0.0486,
                                    0.0329,
                                    0.0213,
                                    0.0131,
                                    0.0074,
                                    0.0034,
                                    0.0003,
                                    0.0000    };
